# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EvdeBakim' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Required by RNFirebase
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Auth', '~> 5.20.1'
pod 'Firebase/Functions', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'
pod 'Firebase/Database', '~> 5.20.1'
pod 'Firebase/Storage', '~> 5.20.1'

  # Pods for EvdeBakim
  # Required by RNFirebase

  target 'EvdeBakim-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'react-native-voice', :path => '../node_modules/react-native-voice'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

  end

  target 'EvdeBakimTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EvdeBakim-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end
