# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EvdeBakim' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Required by RNFirebase
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Auth', '~> 5.20.1'
pod 'Firebase/Functions', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'
pod 'Firebase/Database', '~> 5.20.1'
pod 'Firebase/Storage', '~> 5.20.1'
pod 'GoogleSignIn', '~> 4.4.0'

  # Pods for EvdeBakim
  # Required by RNFirebase



  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'ReactNativePayments', :path => '../node_modules/react-native-payments'

end
